# -*- coding: utf-8 -*-
"""Bot_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1014G4SVs_E1Sg1NLLxR8Pq-gGV0aP7Hu
"""

import csv
import tweepy

#getting the data of followers


def get_followers_info(user_name, number_of_followers) :
    #'''
    consumer_key="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    consumer_secret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    access_key="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    access_secret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    #'''
    
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_key, access_secret)
    api=tweepy.API(auth)

    array_of_info=[]

    number_of_tweets=0
    dummy=0
    
    csvFile=open('info_PK.csv', 'w', newline='')
    csvWriter=csv.writer(csvFile)
    csvWriter.writerow(['user_id', 'id_str', 'followers_count', 'friends_count', 'listed_count', 'favourites_count', 'statuses_count', 'verified'])
    try :
        for tweet in tweepy.Cursor(api.followers, id=user_name).items(number_of_tweets) :
            try :
                info=tweet._json
                user_id=info['id']
                id_str=info['id_str']
                followers_count=tweet.followers_count
                friends_count=tweet.friends_count
                listed_count=tweet.listed_count
                favourites_count=tweet.favourites_count
                verified=tweet.verified
                statuses_count=tweet.statuses_count
                #screen_name=tweet.screen_name
                csvWriter.writerow([user_id, id_str, followers_count, friends_count, listed_count, favourites_count, statuses_count, verified])
                number_of_tweets+=1
                print(number_of_tweets)
                #print(info)
                if number_of_tweets==number_of_followers :
                    break
            except Exception as e :
                print(e)
                dummy=0
    except tweepy.error.RateLimitError as f :
            dummy=1
            csvFile.close()
            print("RateLimit")
    if dummy==0 :
        csvFile.close()
    return array_of_info


i=get_followers_info('@ponguru', 250)

"""# ShashiTaroor"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_ShashiTharoor.csv')

"""# RahulGandhi"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_RahulGandhi.csv')

"""# NarendraModi"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_NarendraModi.csv')

"""# BurkhaDutt"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_BurkhaDutt.csv')

"""# Rajnikanth"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_Rajnikanth.csv')

"""# KTR"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_KTR.csv')

"""# SudheerChaudhary"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_SudheerChaudhary.csv')

"""# RavishKumar"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_RavishKumar.csv')

"""# NitinGadkari"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_NitinGadkari.csv')

"""# PK"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_PK.csv')

"""# ArvindKejriwal"""

import pandas as pd
import numpy as np
import random

train_data = pd.read_csv('info_ArvindKejriwal.csv')
test_data = pd.read_csv('info_ArvindKejriwal.csv')

"""# Machine Learning Code"""

bot_percentage_dic={}
bot_percentage_dic['Arvind Kejriwal']=0
bot_percentage_dic['Rahul Gandhi']=0
bot_percentage_dic['Narendra Modi']=0
bot_percentage_dic['Rajnikanth']=0
bot_percentage_dic['Burkha Dutt']=0
bot_percentage_dic['KTR']=0
bot_percentage_dic['Ravish Kumar']=0
bot_percentage_dic['Sudheer Chaudary']=0
bot_percentage_dic['Nitin Gadkari']=0
bot_percentage_dic['Shashi Tharoor']=0
bot_percentage_dic['PK']=0

train_attr = train_data[['followers_count', 'friends_count', 'listed_count', 'favourites_count', 'statuses_count']]
train_label = train_data[['bot']]

test_attr = test_data[['followers_count', 'friends_count', 'listed_count', 'favourites_count', 'statuses_count']]

from sklearn import tree

clf = tree.DecisionTreeClassifier()

X = train_attr.values
Y = train_label.values
clf = clf.fit(X, Y)

predicted = clf.predict(test_attr)
pred = np.array(predicted)

total=250
bots=0
for i in pred :
    if i==1 :
        bots+=1
print(bots)
print(total)
percentage=(bots*100)/total
print(percentage)

#bot_percentage_dic['Shashi Tharoor']=percentage
#bot_percentage_dic['Rahul Gandhi']=percentage
#bot_percentage_dic['Narendra Modi']=percentage
#bot_percentage_dic['Burkha Dutt']=percentage
#bot_percentage_dic['Rajnikanth']=percentage
#bot_percentage_dic['KTR']=percentage
#bot_percentage_dic['Sudheer Chaudary']=percentage
#bot_percentage_dic['Ravish Kumar']=percentage
#bot_percentage_dic['Nitin Gadkari']=percentage
#bot_percentage_dic['PK']=percentage
bot_percentage_dic['Arvind Kejriwal']=percentage

print(bot_percentage_dic)

