# -*- coding: utf-8 -*-
"""emotion analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1McL3ifjAr3BJmMvXwQ8862cI4PW9ZBKi
"""

# harshit
import csv
import matplotlib.pyplot as plt
import numpy as np
from sklearn import svm
import text2emotion as te

rows=[]
with open('/content/drive/My Drive/RahulGandhi_data.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        rows.append(row)
id=[]
for i in rows:
  #print(i[0],i[1])
  id.append(i[0])
uniqid=[]
for i in range(0,len(id)):
    if id[i] not in uniqid:
        uniqid.append(id[i])
print(uniqid)
retweet1=[]
retweet2=[]
retweet3=[]
retweet4=[]
for i in rows:
    if(uniqid[0]==i[0]):
      #print('ha')
      retweet1.append(i[1])
for i in rows:
    if(uniqid[1]==i[0]):
      retweet2.append(i[1])
for i in rows:
    if(uniqid[2]==i[0]):
      retweet3.append(i[1])
for i in rows:
    if(uniqid[3]==i[0]):
      retweet4.append(i[1])

#print(len(retweet1))

print(retweet1)  
print(retweet2)
print(retweet3)
print(retweet4)

def add_d(d1,d2):
  for i in d1:
    if i in d2:
      d1[i]=d2[i]+d1[i]
    else:
      pass
L1=[0,0,0,0,0]
L2=[0,0,0,0,0]
L3=[0,0,0,0,0]
L4=[0,0,0,0,0]
d1=dict(te.get_emotion(retweet1[0]))
for i in range(1,len(retweet1)):
  D2=dict(te.get_emotion(retweet1[i]))
  if(D2.get('Happy')>0):
    L1[0]+=1
  if(D2.get('Angry')>0):
    L1[1]+=1
  if(D2.get('Surprise')>0):
    L1[2]+=1
  if(D2.get('Sad')>0):
    L1[3]+=1
  if(D2.get('Fear')>0):
    L1[4]+=1
  
  add_d(d1,D2)
print(d1)
d2=dict(te.get_emotion(retweet2[0]))
for i in range(1,len(retweet2)):
  D2=dict(te.get_emotion(retweet2[i]))
  if(D2.get('Happy')>0):
    L2[0]+=1
  if(D2.get('Angry')>0):
    L2[1]+=1
  if(D2.get('Surprise')>0):
    L2[2]+=1
  if(D2.get('Sad')>0):
    L2[3]+=1
  if(D2.get('Fear')>0):
    L2[4]+=1
  add_d(d2,D2)
print(d2)
d3=dict(te.get_emotion(retweet3[0]))
for i in range(1,len(retweet3)):
  D2=dict(te.get_emotion(retweet3[i]))
  if(D2.get('Happy')>0):
    L3[0]+=1
  if(D2.get('Angry')>0):
    L3[1]+=1
  if(D2.get('Surprise')>0):
    L3[2]+=1
  if(D2.get('Sad')>0):
    L3[3]+=1
  if(D2.get('Fear')>0):
    L3[4]+=1
  add_d(d3,D2)
print(d3)
d4=dict(te.get_emotion(retweet4[0]))
s=0
for i in range(1,len(retweet4)):
  D2=dict(te.get_emotion(retweet4[i]))
  if(D2.get('Happy')>0):
    L4[0]+=1
  if(D2.get('Angry')>0):
    L4[1]+=1
  if(D2.get('Surprise')>0):
    L4[2]+=1
  if(D2.get('Sad')>0):
    L4[3]+=1
  if(D2.get('Fear')>0):
    L4[4]+=1
  #s+=(D2.get('Happy'))
  add_d(d4,D2)
print(d4)

print(L1)
print(L2)
print(L3)
print(L4)
#########

pip install text2emotion

print(d1)
k1=d1.keys()
v1=d1.values()
plt.xlabel('EMOTIONS')
plt.ylabel('NO OF COMMENTS')
plt.bar(k1,L1)
plt.show()

print(d2)
k2=d2.keys()
v2=d2.values()
plt.xlabel('EMOTIONS')
plt.ylabel('NO OF COMMENTS')
plt.bar(k2,L2)
plt.show()

print(d3)
k2=d3.keys()
v2=d3.values()
plt.xlabel('EMOTIONS')
plt.ylabel('NO OF COMMENTS')
plt.bar(k2,L3)
plt.show()

print(d4)
k2=d4.keys()
v2=d4.values()
plt.xlabel('EMOTIONS')
plt.ylabel('NO OF COMMENTS')
plt.bar(k2,L4)
plt.show()

pip install text2emotion